detail.html
index.html
login.html
profile.html
static/js/login.js

Change: modify the login.js file

---

static/js/support.js
static/support.css
support.html

Merge: develop <- feature-supports

Merge: develop <- feature-supports

---

.github/workflows/main.yml
README.md
detail.html
index.html
login.html
profile.html
static/detail.css
static/js/detail.js
static/js/listing.js
static/js/login.js
static/js/support.js
static/style.css
static/support.css
support.html

- 댓글 작성 시간 표시하는 방법을 바꿨습니다. 
- 댓글 CRUD에 관한 전반적인 사항을 구현했습니다.

Merge: develop <- feature-comments

---

login.html
static/js/login.js

Style: Login 관련 코드 변수명 카멜케이스로 변경

Style: Login 관련 코드 변수명 카멜케이스로 변경

---

detail.html
index.html
profile.html
static/js/login.js
static/js/navbar.js
static/js/profile_about.js

+ navbar icon 연결 수정, 각 html에 추가
+ 토큰값 수정

Feat: 프로필 업데이트 기능 구현

---

static/detail.css
static/js/detail.js
static/js/login.js

Feat: 좋아요 기능 구현

---

static/js/login.js

Fix: token 추가

---

static/js/detail.js

- 기존에 작성되어 있던 좋아요 기능을 구현하는 함수를 삭제했습니다.

Refactor: 기존 좋아요기능 함수 삭제

---

static/detail.css
static/js/detail.js

- 기존의 좋아요는 클릭시 새로고침이 되었는데 이를 새로고침이 안 되게 수정하였습니다.

Feat: 좋아요 클릭시 새로고침 안 되게 수정

---

static/js/basic.js
static/js/login.js
static/js/profile_about.js

Refactor: 변수명 변경, url 수정

---

static/base.css
static/js/basic.js

Design: 고객관리페이지 이동버튼 nav에 추가

---

profile.html
static/js/detail.js
static/js/profile_about.js

**[자신이 쓴 댓글 모아보기]**
- 프로필 페이지에서 자신이 쓴 댓글을 모아서 볼 수 있습니다.
**[좋아요 기능 에러 수정]**
- 새로고침을 하면 좋아요 했던 것이 초기화되는 에러를 발견했는데 이 부분을 수정했습니다.
**[프로필 페이지에서 자신의 댓글 좋아요 보이기]**
- 프로필 페이지에서 보이는 자신의 댓글에 좋아요 개수도 표기되게 했습니다.

프로필 페이지에서 자신의 댓글만 보이기

---

static/js/detail.js

- [FEAT: detail 페이지 접속시 조회수 증가 기능 구현](https://github.com/2022-Harmony/NewsCommunity-fFinal/commit/dd2b59d42eca9a489a1352bff2cf86bcbe818a81) https://github.com/2022-Harmony/NewsCommunity-fFinal/issues/39

detail 페이지 접속시 조회수 증가 기능 구현

---

detail.html
static/js/detail.js

- 댓글 작성시 페이지 전체 reload 안 되게 수정했습니다.
- detail.html 살짝 수정했습니다.

Refactor: 댓글 작성시 페이지 전체 리로드 안 되게 수정

---

static/js/profile_about.js

[Fix]
- 프로필 업데이트시 사진을 첨부하지 않을 경우 전달되지 않도록 수정 #44

프로필 업데이트되지 않는 오류 해결

---

profile.html
static/js/profile_about.js

- [Fix]
프로필 페이지 타이틀이 해당 회원의 ID로 나오도록 수정
Fixed: #49

프로필 페이지 타이틀 수정

---

static/js/profile_about.js

프로필 페이지에서 볼 수 있는 자신의 댓글에서도 자신의 프로필 사진이 나옵니다.

Feat: 프로필 페이지에서도 자신의 댓글에 사진 나오게 하기

---

static/js/detail.js

Feat: 북마크 여부 조회 기능 추가

---

static/js/detail.js

[FEAT: 북마크 생성 삭제 기능 추가](https://github.com/2022-Harmony/NewsCommunity-fFinal/commit/f349574c6cd62289c18ff10079149a07b8e28547) https://github.com/2022-Harmony/NewsCommunity-fFinal/issues/67
Fixed: #67

FEAT: 북마크 생성 삭제 기능 추가

---

profile.html
static/js/detail.js
static/js/profile_about.js

- [Fix: 프로필 탭중 북마크에 대한 동작이 실행되지 않음 #83](https://github.com/2022-Harmony/NewsCommunity-fFinal/commit/965e1c53e3134c7112a702bff41ee6f35b8429c8)
- js상의 잘못된 구문 수정, 기능에 버그를 만들던 구문 수정
Fixed: #83

Fix: 프로필 탭중 북마크에 대한 동작이 실행되지 않음 #83

---

profile.html
static/js/profile_about.js

프로필 페이지에서 댓글과 북마크 탭을 클릭시 동작이 제대로 안 되던 것을 수정했습니다.
Fixed: #71

Fix: 프로필 페이지에서 댓글, 북마크 탭 제대로 동작 안 하던 것 수정

---

static/js/detail.js
static/js/listing.js
static/js/profile_about.js

[Fix]
- Fix: repsonse 형식 변경에 맞춰 ajax 구문 수정
- Fix: repsonse 형식 변경에 맞춰 ajax 구문 수정 detail관련
- Fix: repsonse 형식 변경에 맞춰 ajax 구문 수정 profile 관련
Fixed: #79

백앤드가 넘겨주는 Response 형식이 변경되어 이를 동기화 해줌

---

static/js/profile_about.js

- 새롭게 Pathvariable을 추가
- 현재 프로필 페이지의 url에 있는 username을 Pathvariable로 넣어줌
Fixed: #85

Fix: ajax call url을 수정

---

static/js/detail.js

: 댓글에서 프로필 사진을 클릭하면 프로필 페이지로 이동합니다. 
<br>
<br>
: 없습니당.
<br>
Fixed: #87
<br>

Feat: 댓글에서 프로필 사진 클릭시 프로필 페이지로 이동

---

static/js/profile_about.js

: 본인의 프로필이 아닌 다른 사용자의 프로필에서 정보가 나오지 않는 부분을 수정했습니다.
<br>
<br>
:보지말아줘요...
<br>
Fixed: #92
<br>
`Merge: develop <- `92/bug_get-profile #93

Fix: 본인의 프로필이 아닌 프로필에서도 다른 사용자의 정보가 나오도록 수정 

---

detail.html
static/js/basic.js
static/js/profile_about.js

: 상세페이지 동작과 관련해서 코드 정리할 것들을 정리했습니다.
<br>
<br>
: 없습니당.
<br>
Fixed: #95 
<br>

Refactor: 상세페이지 관련 코드 정리할 것들 정리 

---

static/js/detail.js

: 서버에 요청해서 가져오는 방식 -> 로컬스토리지에 저장된 거 빼서 쓰는 방식
<br>
<br>
: 없습니다.
<br>
Fixed: #104 
<br>

Refactor: 현재 로그인한 유저의 아이디 가져오는 방식 수정 

---

static/js/basic.js

: 새로고침마다 토큰 갱신하던 방식에서 인가에 문제가 있을 때만 갱신되도록 수정.
문제가 있으면 403에러가 뜨기 때문에 토큰을 갱신하는 함수를 실행하고 일정 시간 이후 에러가 발생한 요청을 다시 실행하도록 했습니다.
<br>
<br>
: 
<br>
Fixed: #106
<br>
`Merge: develop <- `106/fix_refresh-token #107

토큰 갱신 방식 변경

---

static/js/login.js

: 회원 가입 후 로그인 페이지로 정상적인 이동이 되도록 수정했습니다.
<br>
<br>
:
<br>
Fixed: #108
<br>
`Merge: develop <- `108/bug_replace #110

회원 가입 후 이동되는 주소 수정

---

detail.html
static/js/detail.js

: 비로그인시에 화면에 댓글에 작성칸이 보이지 않게 했습니다. 
<br>
<br>
:
<br>
Fixed:  #112 
<br>

비로그인시 화면에 댓글 작성칸 안 보이게 수정

---

detail.html
static/js/detail.js

: 뉴스 상세페이지에서 댓글을 페이징하는 기능입니다.
<br>
<br>
: 
<br>
Fixed: #99 
<br>

뉴스 상세페이지 댓글 페이징 기능 구현

---

static/js/basic.js

: 로그아웃이 응답 결과에 상관없이 처리되도록 했고 토큰 갱신 에러의 경우 로그아웃하도록 했습니다.
<br>
<br>
:
<br>
Fixed: #120
<br>
`Merge: develop <- `120/bug_sign-out #pr번호

토큰 갱신이 불가한 경우에도 로그아웃되지 않는 오류

---

.github/workflows/main.yml
static/js/basic.js

: 테스트용 프론트앤드 배포
<br>
<br>
: 특이사항 없음. 테스트용
<br>
Fixed: 124
<br>
Merge: develop <- deploy_2022-07-22 #125

Feat: 프론트 테스트 배포 

---

profile.html
static/js/profile_about.js
static/profile.css

- 프로필 페이지에서도 댓글 페이징을 했습니다. 
- 아마 이 부분도 댓글이 안 보일텐데 시큐리티 쪽을 좀 수정하면 될 것 같습니다.
<br>
<br>
:
<br>
Fixed: #119 
<br>

프로필 페이지 댓글 모아보기 페이징 기능

---

static/js/detail.js

: 프로필url을 받아오기 위해 요청하는 url에서 api 빠진 것 추가했습니다.
<br>
<br>
:
<br>
Fixed: #130 
<br>

프로필url을 받아오기 위해 요청하는 url에서 api 빠진 것 추가

---

static/js/basic.js

: 토큰이 없으면 헤더에 전달되지 않도록 수정
<br>
<br>
:
<br>
Fixed: #126
<br>
`Merge: develop <- `126/bug_get-news #pr번호

비로그인 사용자 뉴스 조회 불가 오류

---

static/detail.css
static/js/detail.js

: 프로필 사진에 마우스 커서 올리면 손가락 모양으로 마우스 포인터가 바뀝니다.
<br>
<br>
:
<br>
Fixed: #133 
<br>

프로필 사진에 마우스 올려놨을 때 마우스 포인터 변경 

---

static/js/profile_about.js

: 프로필 페이지에서 댓글 보여주기 위한 요청 url 수정
<br>
<br>
:
<br>
Fixed: #135  
<br>

프로필 페이지에서 댓글 보여주기 위한 요청 url 수정

---

static/js/support.js

: Fix: 본인 작성 글에만 수정, 삭제 버튼 나오게 처리
<br>
<br>
: 
<br>
Fixed: 127
<br>

Fix: 본인 작성 글에만 수정, 삭제 버튼 나오게 처리 #127

---

static/js/detail.js
static/js/profile_about.js

: 좋아요 클릭시 하트 모양이 바뀌고 새로고침 해도 유지가 됩니다.
<br>
<br>
:
<br>
Fixed: #132 
<br>

Feat: 좋아요 클릭 시 하트 상태 유지 

---

static/js/profile_about.js
static/profile.css

:  profile.css에 pointer-events: none을 추가했습니다.
<br>
<br>
:
<br>
Fixed: #139 
<br>

Feat: 프로필 페이지에서 보이는 댓글의 좋아요는 클릭이 안 되게 마우스 포인터 막아버리기 

---

.github/workflows/main.yml
detail.html
index.html
login.html
profile.html
static/js/basic.js
static/js/detail.js
static/js/listing.js
static/js/login.js
static/js/profile_about.js
support.html

: deploy test, front
<br>
<br>
: 특이사항 없음
<br>
Fixed: 테스트용 -
<br>

deploy test

---

static/js/login.js

:  내탓 아님, 아무튼 내 잘못 아님
<br>
<br>
:
<br>
Fixed: 
<br>

예진님의 설명 누락으로 인해 발생한 에러 수정

---

detail.html
index.html
login.html
profile.html
static/js/basic.js
static/js/detail.js
static/js/listing.js
static/js/login.js
static/js/profile_about.js
support.html

:  기존 모든 path의 앞에 정의해주었던 /NewsCommunity-fFinal/를 제거,
모든 ajax 요청의 url의 앞에 꾸며지는 settigs.url을 실제 배포 주소인 [https://www.chanhyeoking.com로](https://www.chanhyeoking.xn--com-ky7m/) 변경
<br>
<br>
:  로컬에서 EB 환경으로 배포될 때 프론트의 어떤 요소를 교체해야하는지
<br>
Fixed: #146
<br>
`Merge: develop <- `146/fix_eb-cloudfront-env-sync #147

클라우드 프론트 환경과 EB환경에 맞는 url 환경 구현

---

index.html
static/js/profile_about.js
static/profile.css

: 배포용이지만 미비한 부분이 있어 develop 브랜치와 나누어 deploy_2022-07-22에 배포
<br>
<br>
:  배포용, 특이사항 없음
<br>
Fixed: -
<br>
`Merge: deploy_2022-07-22 <- `#-

배포용 프론트 최종

---

static/js/basic.js

- 상태 코드 잘못 받던 것 수정하고 갱신되면 새로고침되도록 수정
- 갱신 될 때 username 다시 받도록 수정
<br>
<br>
:
<br>
Fixed: #143, #144
<br>
`Merge: develop <- `143/bug refresh token #pr번호

토큰 갱신 관련 오류 해결

---

detail.html
index.html
profile.html
static/js/detail.js
static/js/login.js
static/js/profile_about.js
support.html

:  잔재 삭제 수정 & 좋아요 확인 기능 수정
<br>
<br>
:
<br>
Fixed: 
<br>
`Merge: develop <- `151/bug_check-like #pr번호

잔재 삭제 수정 & 좋아요 확인 기능 수정

---

static/js/detail.js
static/js/profile_about.js

: 좋아요 이력 확인 기능 비로그인 경우 null 반환하지 않도록 수정
<br>
<br>
:
<br>
Fixed: #153
<br>

좋아요 이력 확인 기능 오류

---

detail.html
static/js/detail.js

- 상세페이지에서 댓글 페이징 문제로 많이 지적받은 부분(페이지 번호 관련) 수정
- 정렬 기능 사용하면 페이징 사라지던 것과 하트 아이콘 사라지는 것 수정
<br>
<br>
:
<br>
Fixed:  #166 
<br>

상세페이지 댓글 페이징 개선 및 정렬 기능

---

static/js/profile_about.js

: 프로필 페이지에서 댓글 개수보다 많이 나오는 페이징 번호 locator를 수정했습니다.
<br>
<br>
:
<br>
Fixed: #168 
<br>

프로필 페이지 댓글 페이징 번호 개선

---

static/js/detail.js

: 정렬 기능 구현 방식 수정에 따른 기존 코드 삭제
<br>
<br>
:
<br>
Fixed: #170 
<br>

기존 정렬기능 구현했던 코드 삭제

---

static/js/detail.js

: 로컬로 되어있던 요청 url 주소를 배포 서버 url로 수정함
<br>
<br>
:
<br>
Fixed: #172 
<br>

댓글 요청 url 배포 서버 주소로 수정

---

detail.html
profile.html
static/detail.css
static/js/detail.js
static/js/profile_about.js
static/profile.css

: 페이징 locator와 정렬 옵션 부분에 대해 전반적인 디자인 개선을 시도했습니다.
<br>
<br>
:
<br>
Fixed: #176 
<br>

페이징 locator 와 정렬 부분 디자인 개선

---

static/js/login.js

: 회원 가입 & 가입 시 중복 체크 
기존 request content type이 html 기본 form이었는데 통일을 위해서 json으로 변경했습니다.(백쪽 변경 필요)
<br>
<br>
: 로그인은 할 예정
<br>
Fixed: 해결 중
<br>
`Merge: develop <- `122/refactor_content-type #pr번호

회원 가입 Content-Type Json으로 변경

---

static/js/detail.js

- 다른 사람이 좋아요를 누른 댓글에 내가 좋아요를 하고 바로 취소하면 좋아요의 하트가 비워지지 않았던 오류를 수정
- 배포 서버에는 새로운 API가 없기 때문에 로컬에서 테스트 하려면 basic.js의 요청 url 주소를 localhost:4993으로 변경해줘야함
<br>
<br>
:
<br>
Fixed: #181 
<br>

좋아요 관련 피드백 보완
